Algoritmo "Entrada e Saída de Dados"

// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Jadson de Stefani
// Data atual  : 21/10/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Insira seu nome: ")
   leia(nome)
   escreval("Insira a sua idade: ")
   leia(idade)
   
   escreval("Seu nome é: ", nome)
   escreval("A nota digitada foi: ", idade)
Fimalgoritmo